openapi: 3.0.0
info:
  version: "1.0.0"
  title: Game Room Management API
  description: REST API for managing users, games, slots, bookings, leaderboard, invitations, and notifications.

servers:
  - url: http://localhost:8080/api

tags:
  - name : "Auth"
    description: "Operations related to Authentication and Authorisation"
  - name: "User"
    description: "Operations related to users"
  - name: "Game"
    description: "Operations related to games"
  - name: "Slot"
    description: "Operations related to game slots"
  - name: "Booking"
    description: "Operations related to game bookings"
  - name: "Leaderboard"
    description: "Operations related to leaderboards"
  - name: "Invitation"
    description: "Operations related to invitations"
  - name: "Notification"
    description: "Operations related to notifications"

paths:
  /auth/login:
    post:
      summary: "Admin and User Login"
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Login Successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  role:
                    type : string
                  token:
                    type: string
                    description: "JWT token for authenticated admin"


        "401":
          description: "Unauthorized"

  /auth/signup:
    post:
      summary: "User Signup"
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                phone_no:
                  type: string
                gender:
                  type : string
      responses:
        "201":
          description: "User Created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                    description: "JWT token for authenticated admin"

        "400":
          description: "Bad Request"


  /auth/logout:
    post:
      summary: "User Logout"
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Login Successful"
        "401":
          description: "Unauthorized"

  /users/me:
    get:
      summary: "Get Your profile"
      tags:
        - "User"
      responses:
        "200":
          description: "User Details"
        "404":
          description: "User Not Found"
  /users:
    get:
      summary: "Get All Users"
      tags:
        - "User"
      responses:
        "200":
          description: "User Details"
        "404":
          description: "User Not Found"

  /users/{user_ID}:
    get:
      summary: "Get A Specific user"
      tags:
        - "User"
      parameters:
        - name: user_ID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "User Details"
        "404":
          description: "User Not Found"

  /games:
    get:
      summary: "Get All Games"
      tags:
        - "Game"
      responses:
        "200":
          description: "List of Games"
        "404":
          description: "No Games Found"

    post:
      summary: "Create a Game"
      tags:
        - "Game"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                max_players:
                  type: integer
                min_players:
                  type: integer
                instances:
                  type: integer

      responses:
        "201":
          description: "Game Created"
        "400":
          description: "Bad Request"

  /games/{id}:
    get:
      summary: "Get Game by ID"
      tags:
        - "Game"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Game Details"
        "404":
          description: "Game Not Found"

    put:
      summary: "Update Game Status"
      tags:
        - "Game"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                maxPlayers:
                  type: integer
                min_players:
                  type: integer
                instances:
                  type: integer
                isActive:
                  type: boolean
      responses:
        "200":
          description: "Game Updated"
        "404":
          description: "Game Not Found"

    delete:
      summary: "Delete a Game"
      tags:
        - "Game"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Game Deleted"
        "404":
          description: "Game Not Found"

  /slots/games/{gameID}:
    get:
      summary: "Get Today's Slots for Game"
      tags:
        - "Slot"
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "List of Slots"
        "404":
          description: "Slots Not Found"

  /slots/{id}:
    get:
      summary: "Get Slot by ID"
      tags:
        - "Slot"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Slot Details"
        "404":
          description: "Slot Not Found"

  /bookings:
    post:
      summary: "Make a Booking"
      tags:
        - "Booking"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slot_id:
                  type: string
                game_id:
                  type: string
      responses:
        "201":
          description: "Booking Created"
        "400":
          description: "Bad Request"
        "500":
          description: "Server Error"

  /bookings/upcoming:
    get:
      summary: "Get User's Upcoming Bookings"
      tags:
        - "Booking"
      responses:
        "200":
          description: "List of Bookings"
        "500":
          description: "Server Error"

  /bookings/pending-results:
    get:
      summary: "Get User's Booking which requires to update results"
      tags:
        - "Booking"
      responses:
        "200":
          description: "List of Bookings"
        "500":
          description: "Server Error"

  /leaderboards/games/{game_ID}:
    get:
      summary: "Get Game Leaderboard"
      tags:
        - "Leaderboard"
      parameters:
        - name: game_ID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Leaderboard Details"
        "500":
          description: "Server Error"

  /leaderboards/add-win:
    post:
      summary: "Add win for the user"
      tags:
        - "Leaderboard"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                game_id:
                  type: string
                booking_id:
                  type: string
      responses:
        "200":
          description: "Leaderboard Details"
        "500":
          description: "Server Error"

  /leaderboards/add-loss:
    post:
      summary: "Add loss for the user"
      tags:
        - "Leaderboard"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                game_id:
                  type: string
                booking_id:
                  type: string
      responses:
        "200":
          description: "Leaderboard Details"
        "500":
          description: "Server Error"


  /invitation:
    post:
      summary: "Create an Invitation"
      tags:
        - "Invitation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                invited_user_email:
                  type: string
                slot_id:
                  type: string
                game_id:
                  type: string
      responses:
        "201":
          description: "Invitation Created"
        "400":
          description: "Bad Request"

  /invitations/{id}:
    patch:
      summary: "Update Invitation Status"
      tags:
        - "Invitation"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: "ID of the invitation to update"
        - in: query
          name: action
          required: true
          schema:
            type: string
            enum: [accept, reject]
          description: "Status to update the invitation with (accept or reject)"
      responses:
        "200":
          description: "Invitation Updated Successfully"
        "400":
          description: "Invalid Status Value"
        "404":
          description: "Invitation Not Found"
        "500":
          description: "Server Error"

  /invitations:
    get:
      summary: "Get User pending Invitations"
      tags:
        - "Invitation"
      responses:
        "200":
          description: "List of Notifications"
        "500":
          description: "Server Error"


  /notifications:
    get:
      summary: "Get User Notifications"
      tags:
        - "Notification"
      responses:
        "200":
          description: "List of Notifications"
        "500":
          description: "Server Error"
